name: Trigger 1000 Workflow Runs with GH CLI
on:
  workflow_dispatch:
    inputs:
      total_runs:
        description: 'Number of workflow runs to trigger'
        required: true
        default: '1000'
        type: number

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Authenticate with GitHub CLI using PAT
      run: |
        echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        gh auth status

    - name: Trigger workflow runs
      run: |
        total_runs=${{ inputs.total_runs }}
        workflow_file="main.yml"  # Change to your workflow filename
        
        for i in $(seq 1 $total_runs); do
          echo "🚀 Triggering workflow run $i/$total_runs"
          
          # Trigger the workflow
          gh workflow run $workflow_file --ref main
          
          if [ $? -eq 0 ]; then
            echo "✅ Successfully triggered run $i"
          else
            echo "❌ Failed to trigger run $i"
          fi
          
          # Add delay to avoid rate limiting
          sleep 2
        done

    - name: Completion message
      run: |
        echo "🎉 Started triggering ${{ inputs.total_runs }} individual workflow runs!"
        echo "They will appear as separate runs in your Actions tab."
