name: Trigger Multiple Workflows
on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Number of workflow runs to trigger'
        required: true
        default: '1000'
        type: number

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Trigger multiple workflow runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        import os
        import requests
        import json
        import time

        count = ${{ inputs.count }}
        repo = os.environ['GITHUB_REPOSITORY']
        token = os.environ['GITHUB_TOKEN']

        headers = {
            'Authorization': f'token {token}',
            'Accept': 'application/vnd.github.v3+json'
        }

        for i in range(1, count + 1):
            url = f'https://api.github.com/repos/{repo}/actions/workflows/main.yml/dispatches'
            data = {
                'ref': 'main'  # or your branch name
            }
            
            response = requests.post(url, headers=headers, json=data)
            
            if response.status_code == 204:
                print(f'✅ Successfully triggered workflow run {i}/{count}')
            else:
                print(f'❌ Failed to trigger workflow {i}: {response.status_code} {response.text}')
            
            # Add a small delay to avoid rate limiting
            time.sleep(0.5)
      shell: python

    - name: Completion message
      run: |
        echo "🎉 Started triggering ${{ inputs.count }} separate workflow runs!"
        echo "They will appear as individual runs in your Actions tab."
