name: Trigger 1000 Workflow Runs
on:
  workflow_dispatch:
    inputs:
      total_runs:
        description: 'Number of workflow runs to trigger'
        required: true
        default: '1000'
        type: number

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Trigger 1000 workflow runs
      env:
        PAT: ${{ secrets.GH_PAT }}
      run: |
        import os
        import requests
        import time

        total_runs = ${{ inputs.total_runs }}
        repo = os.environ['GITHUB_REPOSITORY']
        token = os.environ['PAT']
        workflow_file = 'main.yml'  # Change this to your workflow filename

        headers = {
            'Authorization': f'token {token}',
            'Accept': 'application/vnd.github.v3+json',
            'X-GitHub-Api-Version': '2022-11-28'
        }

        url = f'https://api.github.com/repos/{repo}/actions/workflows/{workflow_file}/dispatches'

        for i in range(1, total_runs + 1):
            data = {
                'ref': 'main'  # Change to your branch name if different
            }
            
            try:
                response = requests.post(url, headers=headers, json=data)
                
                if response.status_code == 204:
                    print(f'✅ Successfully triggered workflow run {i}/{total_runs}')
                else:
                    print(f'❌ Failed to trigger workflow {i}: {response.status_code} {response.text}')
                    # Continue trying despite errors
                    
            except Exception as e:
                print(f'❌ Error triggering workflow {i}: {str(e)}')
            
            # Add delay to avoid rate limiting (adjust as needed)
            time.sleep(2)  # 2 seconds between triggers

        print(f'🎉 Attempted to trigger {total_runs} workflow runs!')
      shell: python
